# Nombre archivo: docker-compose.yml
version: "3.3"
services:
  db:
    image: mariadb
    # Nombre de los contenedores para diferenciarlos facilmente
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_PASSWORD: root
    # vamos a guardar los datos de nuestra base de datos en nuestro sistema de archivos
    # el uso de estos volúmenes con nombre se ubicará de forma predeterminada en algún lugar de los archivos acoplables de su sistema
    volumes:
      - dbdata:/var/lib/mysql

  wordpress:
    image: wordpress:6.4.2-php8.1-fpm-alpine
    # wordpress debe esperar una conexión a la base de datos
    depends_on:
      - db
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      # vamos a guardar nuestra carpeta de wordpress en nuestro sistema de archivos
      - ./my-web-site/wp:/var/www/html
      # vamos a poner nuestro tema personalizado en la carpeta de temas
      - ./my-web-site/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress_db

  webserver:
    # nginx necesita que WordPress se inicie primero
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    # abrirmos los puertos de nginx para acceder a nuestro sitio
    # podemos cambiar nuestros puertos para modo desarrollo
    # solo debemos asegurarnos de escucharlos en nginx
    ports:
      - "80:80" # para http
      - "443:443" # para https
    volumes:
      # también montaremos wordpress en nginx
      # carpeta html para exponerlo
      - ./my-web-site/wp:/var/www/html
      # agregamos nuestra propia carpeta nginx-config.
      - ./my-web-site/nginx-conf/:/etc/nginx/conf.d # nginx ocupará estos certificados para el protocolo https
      - ./my-web-site/certs:/etc/nginx/certs

volumes:
  wordpress:
  dbdata:
  